### ISSUE TITLE
Enhancement for Gigabyte Biosses?

### ISSUE THREAD

**Issue by Reaxer** [hahagu/AsusBiosScraper#1]
Hi!
I like your project, but sadly I have a gigabyte board. 

Would it be possible (if easy) to add gigabyte boards?
Links for the bioses are pretty simple.
Bioses for my board, the B550 Aorus Elite V2
https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f13.zip and
https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f14e.zip
AGESA 1.2.0.5 would probably be https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f15.zip

Thanks in advance!
Reaxer

**Comment by hahagu** [comment]
Will look into it!

**Comment by hahagu** [comment]
> Hi! I like your project, but sadly I have a gigabyte board.
> 
> Would it be possible (if easy) to add gigabyte boards? Links for the bioses are pretty simple. Bioses for my board, the B550 Aorus Elite V2 https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f13.zip and https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f14e.zip AGESA 1.2.0.5 would probably be https://download.gigabyte.com/FileList/BIOS/mb_bios_b550-aorus-elite-v2_f15.zip
> 
> Thanks in advance! Reaxer

Unfortunately, Gigabyte does not seem to expose the internal motherboards & bios list to the public.
Therefore, it can be safely said that searching for boards is impossible in a practical manner, as it is with Asus boards. 
Also, one other problem is that some files have different extensions (such as with your example, f14e).
The tool currently needs to run `links searched * 2` amount of links, since the website differentiates between `.zip` and `.ZIP`.
Adding another extension will make the scan far slower, as one extension adds to the `n` in `links searched * n`.

If you find a solution to these problems, such as finding the bios download list to be parsed, I will look into it again.
